'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
process.chdir(path.join(__dirname, '..'));
const html = fs.readFileSync('index.html', 'utf8');
const scripts = [...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m => m[1]);
assert(scripts.length >= 3, 'bundled crypto, ZIP and application scripts must exist');
for (const [i, script] of scripts.entries()) new vm.Script(script, { filename: `inline-${i}.js` });
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
assert.equal(new Set(ids).size, ids.length, 'duplicate DOM IDs');
const main = scripts.at(-1);
for (const ref of main.matchAll(/\$\("([^"]+)"\)/g)) assert(ids.includes(ref[1]), `missing element ${ref[1]}`);
assert(!/<script\b[^>]*\bsrc=/i.test(html), 'offline file must not depend on remote scripts');
assert(!/<(?:link|img)\b[^>]*(?:href|src)="https?:/i.test(html), 'no runtime remote assets');
for (const mode of ['system', 'light', 'dark']) assert(html.includes(`data-theme="${mode}"`) || main.includes(`"${mode}"`));
const quoteMatch = main.match(/function shellQuote\(value\) \{[\s\S]*?\n\}/);
assert(quoteMatch, 'shellQuote helper missing');
const context = vm.createContext({});
vm.runInContext(quoteMatch[0], context);
assert.equal(context.shellQuote("a'b"), "'a'\\''b'");
assert.equal(context.shellQuote('$(whoami)'), "'$(whoami)'");
assert(main.includes('parseOpenSshEd25519'), 'OpenSSH private key validation missing');
assert(main.includes('不匹配'), 'mismatch rejection missing');
assert(!main.includes('当前用户: $(whoami)'), 'remote username must not expand locally');
for (const name of ['LICENSE', 'Dockerfile', 'compose.yaml', '.env.example', 'nginx.conf', 'install.sh', 'deploy/install.sh']) assert(fs.existsSync(name), `missing ${name}`);
console.log(`PASS: ${scripts.length} inline scripts, ${ids.length} DOM IDs; offline dependencies, shell quoting and deployment files checked.`);
